version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/buildex
    binary: buildex
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats: ["tar.gz"]

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: x-qdo
    name: buildex
  draft: false
  prerelease: auto
  mode: replace
